version: '3.2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 3000:3000
    volumes:
     - .:/app/
